data:
  reference_fasta: /home/fcruz/projects/xyrichtys_novacula/mitogenome/data/reference/Thalassoma_lunare_mitochondrion.fasta
  ont: /home/fcruz/projects/xyrichtys_novacula/assembly/mitogenome/data/reads/ont/ont.filtlong.fastq.gz 
  ill_1: /home/fcruz/projects/xyrichtys_novacula/assembly/mitogenome/data/reads/illumina/reads.illumina.1.fastq.gz 
  ill_2: /home/fcruz/projects/xyrichtys_novacula/assembly/mitogenome/data/reads/illumina/reads.illumina.2.fastq.gz
parameters:
  ontfilter_minmatch: 8000
  ontfilter_minq: 13
  flye_opts: " --resume --scaffold -i 2"
  reference_length: 17073
  mito_length_variation: 1500
annotation:
  genetic_code: 2
  mitos_options: " --linear --best"
  refseq_database : refseq81m
